site_name: Reefer Container Predictive Maintenance
repo_url: https://github.com/ibm-cloud-architecture/refarch-reefer-ml
nav:
  - Introduction: index.md
  - Collect data: collect-data.md
  - Define the predictive scoring model: /#2-define-the-predictive-scoring-model
  - Build and run the solution on Openshift: build-run.md
  - Run integration tests: integration-tests.md
  - Reefer predictive maintenance problem: predictive-maintenance.md
  - Reefer solution implementation project: https://ibm-cloud-architecture.github.io/refarch-kc/
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences