site_name: Reefer Container Predictive Maintenance
repo_url: https://github.com/ibm-cloud-architecture/refarch-reefer-ml
nav:
  - Introduction: index.md
  - Run integration tests: integration-tests.md
  - Reefer Container Predictive Maintenance: predictive-maintenance.md
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences