version: '3'
services:
    simulator:
        image: ibmcase/reefersimulator:latest
        hostname: reefersimulator
        ports:
            - "8080:8080"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
            KAFKA_APIKEY: ""