version: '3'
services:
    simulator:
        image: ibmcase/reefersimulator:latest
        hostname: reefersimulator
        ports:
            - "8080:8080"
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
    containerconsumer:
        image: ibmcase/containerconsumer:latest
        hostname: containerconsumer
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
    scoring:
        image: ibmcase/predictivescoring:latest
        hostname: scori
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
    scoringweb:
        image: ibmcase/predictivescoringweb:latest
        hostname: scoringweb
        ports:
            - "8082:8083"
        environment:
            PREDICT_WEB_PORT: "8083"